nome = str(input("nome do atleta: "))
s1 = float(input("primeiro salto: "))
s2 = float(input("segundo salto: "))
s3 = float(input("terceiro salto: "))
s4 = float(input("quarto salto: "))
s5 = float(input("quinto salto: "))
media = (s1 + s2 + s3 + s4 + s5)
media2 = (media/5)
print("Resultado:")
print("Atleta: %s"% nome)
print("saltos:", s1, s2, s3, s4, s5)
print("media: ", media2)
